[build]
    command = "ELEVENTY_ENV=prod yarn build"
    publish = "dist"

[dev]
    command = "yarn start"
    autoLaunch = false

[[redirects]]
    from = "/.well-known/*"
    to = "/wellknown/:splat"
    status = 200
    force = true

[[redirects]]
    from = "https://kotimbercahaya.netlify.app/*"
    to = "https://kotimbercahaya.net/:splat"
    status = 301
    force = true
