[build]
    command = "ELEVENTY_ENV=prod yarn build"
    publish = "dist"

[dev]
    command = "yarn start"
    autoLaunch = false

[[redirects]]
    from = "/.well-known/*"
    to = "/wellknown/:splat"
    status = 200
    force = true
